---
title: "Untitled"
author: "Abhay Padda"
date: "24 January 2018"
output:
  word_document: default
  html_document:
    df_print: paged
---

# Simple program in R to fetch tweets from any twitter handle 

```{r message=FALSE, warning=FALSE}
##twitteR package gets the tweets 
library("twitteR")
## ROAuth helps in establishing connection with twitter and other social media sites
library("ROAuth")

## Set Options
options(httr_oauth_cache=T)

```
### Set API Keys
``` {r echo=FALSE}

api_key <- "5HvzVjkQk0UODChhQLCMBo04m"
api_secret <- "RbhFvyYE1xZpiTpAs1HWc0zbI9g62WaGJavNvJu957fRZgYmYv"
access_token <- "160516034-BNjXJBamKQQEeE3THfJ88zKLXBE1CFaLnuIc35it"
access_token_secret <- "AykvyBz9vsOAlsNhwnjh6RYKbKjw81H3JsuUuoLGacrks"

```

#### To access data from Twitter we need to get API keys which can be generated by creating a new app at https://apps.twitter.com/ 
``` {r}

# Set API Keys
#api_key <- "******"
#api_secret <- "******"
#access_token <- "******"
#access_token_secret <- "*****"

setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

```

```{r message=FALSE, warning=FALSE}
# Set search string
search.string <- "@MakeMyTripIndia"

# Get 5 tweets on the MMT handle
tweets <- searchTwitter(search.string, n=5, lang="en", since=NULL, until=NULL, retryOnRateLimit=10)

## Let's check the data in the tweets object
head(tweets)

## Get 100 tweets where this word has been used
ut <- userTimeline('MakeMyTripIndia', n=100)

mmt_df <- do.call("rbind", lapply(ut, as.data.frame))

## Let's check the column names in the usertimeline data frame
names(mmt_df)

## Let's view the first 10 rows
head(mmt_df, n =10)
```

